hostname: icdvm-vc08
username: administrator@vsphere.local
password: 8E*P2?5kit
datacenter: iCod 6.5

src_repository: /products/scripts/AgentEmss
fs_emss: /opt/cheops/patchagent

file_system: ext4
vg_name: vg_emss
lv_name: lv_emss

pkg_dest: /tmp

ip_emss: 192.168.15.47
file_src_emss: UnixPatchAgent83057.tar

java_folder: /usr/lib/jvm
java_name: jre1.8.0_211